# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  xcodeproj = "./ios/Bits.xcodeproj"

  skip_docs

  # TODO: develop lane

  %w(major minor patch).each do |part|
    desc "Bump #{part} version"
    lane "bump_#{part}".to_sym do
      sh("npm version #{part} --no-git-tag-version")
      new_version = increment_version_number(
        xcodeproj: xcodeproj,
        bump_type: part
      )
      commit_version_bump(
        xcodeproj: xcodeproj,
        include: %w(package.json package-lock.json),
        message: "Bump version to #{new_version}"
      )
    end
  end

  desc "Upload build to TestFlight"
  lane :release do
    sync_code_signing(
      type: "appstore",
      readonly: true
    )
    increment_build_number(
      xcodeproj: xcodeproj,
      build_number: `date +%s`
    )
    build_ios_app(
      project: xcodeproj,
      scheme: "Bits",
    )
    changelog_from_git_commits(
      merge_commit_filtering: "exclude_merges"
    )
    upload_to_testflight
  end

  # TODO: Submit lane
end
