# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

skip_docs

default_platform(:ios)

platform :ios do
  config = {
    :app_identifier => {
      :debug => "com.chunkhang.bits.debug",
      :release => "com.chunkhang.bits",
    },
    :project => "./ios/Bits.xcodeproj",
    :workspace => "./ios/Bits.xcworkspace",
    :scheme => "Bits",
    :build_directory => "./ios/build",
    :build_name => "bits.ipa",
    :readonly => is_ci,
  }

  desc "Build and archive app"
  private_lane :build do |options|
    sync_code_signing(
      type: options[:release] ?
        "appstore" : "development",
      app_identifier: options[:release] ?
        config[:app_identifier][:release] :
        config[:app_identifier][:debug],
      readonly: config[:readonly]
    )
    build_ios_app(
      configuration: options[:release] ?
        "Release" : "Debug",
      export_method: options[:release] ?
        "app-store" : "development",
      workspace: config[:workspace],
      scheme: config[:scheme],
      output_directory: config[:build_directory],
      output_name: config[:build_name],
      clean: true,
      silent: true,
    )
    sh("rm -r '#{lane_context[SharedValues::XCODEBUILD_ARCHIVE]}'")
  end

  desc "Install app onto device"
  lane :install do
    build(release: false)
    install_on_device(
      ipa: "#{config[:build_directory]}/#{config[:build_name]}",
      skip_wifi: true,
    )
  end

  %w(major minor patch).each do |part|
    desc "Bump #{part} version"
    lane part.to_sym do
      sh("npm version #{part} --no-git-tag-version")
      new_version = increment_version_number(
        xcodeproj: config[:project],
        bump_type: part,
      )
      commit_version_bump(
        xcodeproj: config[:project],
        include: %w(package.json package-lock.json),
        message: "Bump version to #{new_version}",
      )
    end
  end

  desc "Upload build to TestFlight"
  lane :beta do
    build(release: true)
    increment_build_number(
      xcodeproj: config[:project],
      build_number: `date +%s`,
    )
    changelog_from_git_commits(
      merge_commit_filtering: "exclude_merges",
    )
    upload_to_testflight(
      ipa: "#{config[:build_directory]}/#{config[:build_name]}",
    )
  end

  # desc "Promote latest build to App Store"
  # lane :release do
  #   upload_to_apps_store
  # end
end
