name: Build

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.16.0
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.0
      - run: npm install
      - run: npm run lint
