name: Release

on:
  push:
    branches:
      - 'release/**'

jobs:
  release-ios:
    runs-on: macOS-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js 12.16.1
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.1

      - name: Use Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install Node.js dependencies
        run: npm install

      - name: Install Ruby dependencies
        run: bundle install

      - name: Run fastlane beta
        run: bundle exec fastlane beta
